services:
    redis:
        image: "redis"
        platform: linux/amd64
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        env_file: .env
        entrypoint: redis-server --requirepass ${REDIS_PWD}
        networks:
            app-network:
                ipv4_address: 10.170.2.150

    nginx:
        image: nginx:latest
        platform: linux/amd64
        container_name: nginx
        restart: always
        ports:
            - "8001:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./.log:/var/log/nginx
            - ./shell_scripts:/shell_scripts
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
        networks:
            app-network:
                ipv4_address: 10.170.2.151

networks:
    app-network:
        external: true
