services:
    backend_v2:
        build:
            context: .
            platforms:
                - linux/amd64
        image: backend_v2:latest
        container_name: backend_v2
        restart: always
        env_file: .env
        ports:
            - "8082:8080"
        volumes:
            - .:/app
        entrypoint: python main.py
        networks:
            app-network:
                ipv4_address: 10.170.2.153

networks:
    app-network:
        external: true
